import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { replay } from '../src/index';
import { goldenConfig, goldenEvents } from './golden-script';

/**
 * The golden replay fixture: a recorded event log plus the sha-256 of every
 * post-event state. Replaying the log must reproduce every hash — that is
 * bit-identical determinism, asserted, not hoped for.
 *
 * One honest caveat: the engine uses Math.exp for decay, and ECMA-262 does
 * not pin transcendental functions to the last bit across engines. sqrt is
 * correctly rounded and safe; exp is deterministic within an engine (CI and
 * this fixture both run V8). If cross-engine bit-identity ever matters, the
 * fix is a software exp in core — noted in ADR-0001, not needed yet.
 *
 * Regenerate with `npm run golden:update`, and only when the model itself
 * intentionally changes. A surprise diff here is a bug, not staleness.
 */

const FIXTURE_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  'fixtures',
  'golden-replay.json',
);

function sha256(text: string): string {
  return createHash('sha256').update(text).digest('hex');
}

function computeFixture() {
  const config = goldenConfig();
  const events = goldenEvents();
  const { states, fires } = replay(config, events);
  return {
    note: 'Generated by core/test/golden-script.ts via `npm run golden:update`. Do not edit by hand.',
    config,
    events,
    stateHashes: states.map((state) => sha256(JSON.stringify(state))),
    fires,
    finalState: states[states.length - 1],
  };
}

describe('golden replay', () => {
  if (process.env.UPDATE_GOLDEN) {
    it('regenerates the fixture', () => {
      const fixture = computeFixture();
      writeFileSync(FIXTURE_PATH, `${JSON.stringify(fixture, null, 2)}\n`);
      expect(fixture.stateHashes.length).toBeGreaterThan(0);
      expect(fixture.fires.length).toBeGreaterThan(2);
    });
    return;
  }

  if (!existsSync(FIXTURE_PATH)) {
    it('the fixture exists', () => {
      expect.fail(`missing golden fixture at ${FIXTURE_PATH} — run \`npm run golden:update\``);
    });
    return;
  }

  const fixture = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8'));

  it('replaying the recorded log reproduces every state bit-for-bit', () => {
    // Replays the fixture's own copy of the log: the fixture is self-contained
    // and does not depend on the embedder that produced it.
    const { states, fires } = replay(fixture.config, fixture.events);
    const hashes = states.map((state) => sha256(JSON.stringify(state)));
    expect(hashes).toEqual(fixture.stateHashes);
    expect(JSON.parse(JSON.stringify(fires))).toEqual(fixture.fires);
    expect(JSON.parse(JSON.stringify(states[states.length - 1]))).toEqual(fixture.finalState);
  });

  it('the scripted session still produces the recorded log (embedder-drift tripwire)', () => {
    const live = JSON.parse(JSON.stringify({ config: goldenConfig(), events: goldenEvents() }));
    expect(live).toEqual({ config: fixture.config, events: fixture.events });
  });
});
